// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmuqLGrwncuOQumEUwVld2j-dsAzFG3lI',
    appId: '1:82340952469:ios:3a95ca2588170082a29e9c',
    messagingSenderId: '82340952469',
    projectId: 'zenzone-1',
    storageBucket: 'zenzone-1.appspot.com',
    androidClientId: '82340952469-mcvbbishc1fe68k7ni5utt6ipqcmpn7d.apps.googleusercontent.com',
    iosClientId: '82340952469-gl2971d791l8tnqv1focnbtfkhrvm9mq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4wP9WWHF5HuUrzCjczHCCNpItUglrSQE',
    appId: '1:82340952469:web:9e8c9f590bdab746a29e9c',
    messagingSenderId: '82340952469',
    projectId: 'zenzone-1',
    authDomain: 'zenzone-1.firebaseapp.com',
    storageBucket: 'zenzone-1.appspot.com',
    measurementId: 'G-4PRM2L87M4',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMch7hOxNwN4NvOTVl_winQtlVOOQqXeY',
    appId: '1:82340952469:web:3269c82193d53c5fa29e9c',
    messagingSenderId: '82340952469',
    projectId: 'zenzone-1',
    authDomain: 'zenzone-1.firebaseapp.com',
    storageBucket: 'zenzone-1.appspot.com',
    measurementId: 'G-HES16L16BF',
  );

}